use crate::source::PHP_CS_FIXER_TAG;
use crate::spec::KindSpec;
use crate::Record;

/// Render the generated source for one kind.
pub(crate) fn render(spec: &KindSpec, records: &[Record], sha: &str) -> String {
    let mut out = String::new();
    out.push_str(&header(spec, records.len(), sha));
    for r in records {
        let version = |v: Option<(u8, u8)>| match v {
            Some((major, minor)) => format!("Some(PhpVersion::minor({major}, {minor}))"),
            None => "None".to_string(),
        };
        let replacement = match r.replacement {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "    ({:?}, Availability {{ added: {}, deprecated: {}, removed: {}, replacement: {}, extension: {:?}, compiler_optimized: {} }}),\n",
            r.name,
            version(r.added),
            version(r.deprecated),
            version(r.removed),
            replacement,
            r.extension,
            r.compiler_optimized,
        ));
    }
    out.push_str("];\n");
    out
}

/// The per-kind generated-file header. The function header is reproduced
/// byte-for-byte from the M2 generator so regeneration leaves `functions.rs`
/// unchanged; the constant header is its parallel.
fn header(spec: &KindSpec, n: usize, sha: &str) -> String {
    match spec.label {
        "function" => format!(
            "// @generated by tools/regenerate - DO NOT EDIT BY HAND.\n\
             //\n\
             // Native PHP function availability for PHP 7.4 through 8.5.\n\
             //\n\
             // Names, per-version presence, isDeprecated and (so) added/deprecated/\n\
             // removed: JetBrains phpstorm-stubs (Apache-2.0) @ {sha}, reflection\n\
             // caches tests/cache/Reflection*.json, cross-checked against\n\
             // PHPCompatibility (LGPL-3.0, version facts only, never copied).\n\
             // Extensions and @since: the same repo's tests/cache/StubsFunctions.json.\n\
             // compiler_optimized: PHP-CS-Fixer (MIT) NativeFunctionInvocationFixer\n\
             // @compiler_optimized set @ {tag}.\n\
             // replacement: editorial, from the PHP manual and stub @deprecated\n\
             // messages (terse labels, never copied prose); see NOTICE.\n\
             //\n\
             // Regenerate with `cargo run -p regenerate --\n\
             // <phpstorm-stubs checkout> <phpcompatibility checkout>`; see NOTICE and\n\
             // tools/regenerate/README.md. {n} functions.\n\n\
             use crate::{{Availability, PhpVersion}};\n\n\
             // One row per function keeps the table reviewable and diff-friendly on\n\
             // regeneration; rustfmt would otherwise explode each row across lines.\n\
             #[rustfmt::skip]\n\
             pub(crate) static FUNCTIONS: &[(&str, Availability)] = &[\n",
            sha = sha,
            tag = PHP_CS_FIXER_TAG,
            n = n,
        ),
        "constant" => format!(
            "// @generated by tools/regenerate - DO NOT EDIT BY HAND.\n\
             //\n\
             // Native PHP constant availability for PHP 7.4 through 8.5.\n\
             //\n\
             // Names and per-version presence (so added/removed): JetBrains\n\
             // phpstorm-stubs (Apache-2.0) @ {sha}, reflection caches\n\
             // tests/cache/Reflection*.json, cross-checked against PHPCompatibility\n\
             // (LGPL-3.0, version facts only, never copied).\n\
             // Extensions and the corroborating @since/@removed: the same repo's\n\
             // tests/cache/StubsConstants.json.\n\
             // deprecated and replacement: editorial, from the PHP manual and stub\n\
             // phpDoc @deprecated messages (terse labels, never copied prose). The\n\
             // reflection caches carry no constant deprecation flag and\n\
             // PHPCompatibility ships no constant-deprecation sniff, so neither is\n\
             // machine-derived or cross-checked. See NOTICE.\n\
             // Constant names are case-sensitive: stored and matched by exact bytes.\n\
             // compiler_optimized is always false for constants.\n\
             //\n\
             // Regenerate with `cargo run -p regenerate --\n\
             // <phpstorm-stubs checkout> <phpcompatibility checkout>`; see NOTICE and\n\
             // tools/regenerate/README.md. {n} constants.\n\n\
             use crate::{{Availability, PhpVersion}};\n\n\
             // One row per constant keeps the table reviewable and diff-friendly on\n\
             // regeneration; rustfmt would otherwise explode each row across lines.\n\
             #[rustfmt::skip]\n\
             pub(crate) static CONSTANTS: &[(&str, Availability)] = &[\n",
            sha = sha,
            n = n,
        ),
        "class" => format!(
            "// @generated by tools/regenerate - DO NOT EDIT BY HAND.\n\
             //\n\
             // Native PHP class, interface and enum availability for PHP 7.4\n\
             // through 8.5, collapsed into one case-insensitive table.\n\
             //\n\
             // Names and per-version presence (so added/removed): JetBrains\n\
             // phpstorm-stubs (Apache-2.0) @ {sha}, reflection caches\n\
             // tests/cache/Reflection*.json (PHPClass, PHPInterface, PHPEnum),\n\
             // cross-checked against PHPCompatibility (LGPL-3.0, version facts\n\
             // only, never copied).\n\
             // Extensions and the corroborating @since/@removed: the same repo's\n\
             // tests/cache/StubsClasses.json.\n\
             // deprecated and replacement: editorial, from the PHP manual (terse\n\
             // labels, never copied prose). The reflection caches carry no usable\n\
             // class deprecation flag and PHPCompatibility ships no class-\n\
             // deprecation sniff, so neither is machine-derived. See NOTICE.\n\
             // Class names are case-insensitive: stored and matched lowercased.\n\
             // compiler_optimized is always false for classes.\n\
             //\n\
             // Regenerate with `cargo run -p regenerate --\n\
             // <phpstorm-stubs checkout> <phpcompatibility checkout>`; see NOTICE and\n\
             // tools/regenerate/README.md. {n} classes.\n\n\
             use crate::{{Availability, PhpVersion}};\n\n\
             // One row per class keeps the table reviewable and diff-friendly on\n\
             // regeneration; rustfmt would otherwise explode each row across lines.\n\
             #[rustfmt::skip]\n\
             pub(crate) static CLASSES: &[(&str, Availability)] = &[\n",
            sha = sha,
            n = n,
        ),
        other => unreachable!("unknown kind label {other}"),
    }
}
